module.exports = [
	"/guis.common/libraries/jquery/jquery.js",
	"/guis.common/libraries/jquery/jquery-ui.js",
	"/guis.common/libraries/jquery/plugins/jquery.jPopover.js",
    "/guis.common/libraries/jquery/plugins/jsTree/jquery.jstree.js",
    "/guis.common/libraries/moment.min.js",
    "/guis.common/libraries/underscore/underscore-min.js",
    "/guis.common/libraries/jquery/plugins/jquery.autogrow.js",
    "/guis.common/libraries/jquery/plugins/jquery.jeditable.js",
    "/guis.common/libraries/jquery/plugins/jquery.jeditable.autogrow.js",
    "/guis.common/libraries/jquery/plugins/jquery.dotdotdot.js",
	"/guis.common/libraries/jquery/plugins/jquery.svg.min.js",
	"/guis.common/libraries/jquery/plugins/jquery.svgdom.min.js",
	// "/guis.common/libraries/jquery/plugins/jquery.svgfilter.min.js",
	"/guis.common/libraries/jquery/plugins/jquery.svganim.min.js",
	"/guis.common/libraries/jquery/plugins/jquery.color.js",
	"/config.default.js",
	"/config.local.js",
	"/Helper.js",
	"/Dispatcher.js",
	"/ObjectManager.js",
	"/SocketClient.js",
	"/../Common/Log.js",
	"/../Common/DataSet.js",
	"/../Common/ActionManager.js",
	"/../Common/AttributeManager.js",
	"/../Common/TranslationManager.js"
]