GeneralObject.setTranslations('de',{
	'GraphicalObject':'Grafisches Objekt',
	'name':'Name',
	'type':'Typ',
	'layer':'Ebene',
	'width':'Breite',
	'height':'Höhe',
	'fillcolor':'Füllfarbe',
	'linecolor':'Linienfarbe',
	'linesize':'Linienstärke',
	'font-family':'Schriftart',
	'font-size':'Schriftgröße',
	'font-color':'Schriftfarbe',
	'Delete':'Löschen',
	'Duplicate':'Duplizieren',
	'Follow':'Folgen',
	'Edit':'Bearbeiten',
	'Link':'Verknüpfen',
	'to front':'Nach vorne',
	'to back':'Nach hinten',
	'locked':'Angeheftet',
	'visible':'Sichtbar',
	'group':'Gruppe',
	'shadow':'Schatten',
	'hidden':'Versteckt',
	'id':'ID',
	'x':'X Pos.',
	'y':'Y Pos.',
	'link':'Verknüpfung',
	'no object slected':'Kein Objekt ausgewählt',
	'you need at least one link from or to this object to hide it':'Es muss mindestens eine Verknüpfung von oder zu diesem Objekt existieren, um es zu verstecken.',
	'mimeType' : 'Dateityp',
	'preview' : 'Vorschau'
}
);