GeneralObject.setTranslations('de',{
	'GraphicalObject':'Grafisches Objekt',
	'name':'Name',
	'type':'Typ',
	'layer':'Ebene',
	'width':'Breite',
	'height':'Höhe',
	'fillcolor':'Füllfarbe',
	'linecolor':'Linienfarbe',
	'opacity':'Deckkraft',
	'linesize':'Linienstärke',
	'font-family':'Schriftart',
	'font-size':'Schriftgröße',
	'font-color':'Schriftfarbe',
	'Delete':'Löschen',
	'Duplicate':'Duplizieren',
	'Follow':'Folgen',
	'Edit':'Bearbeiten',
	'Link':'Verknüpfen',
	'to front':'Nach vorne',
	'to back':'Nach hinten',
	'locked':'Angeheftet',
	'visible':'Sichtbar',
	'group':'Gruppe',
	'Group':'Gruppieren',
	'Ungroup':'Gruppierung aufheben',
	'shadow':'Schatten',
	'hidden':'Versteckt',
	'id':'ID',
	'x':'X Pos.',
	'y':'Y Pos.',
	'link':'Verknüpfung',
	'no object slected':'Kein Objekt ausgewählt',
	'you need at least one link from or to this object to hide it':'Es muss mindestens eine Verknüpfung von oder zu diesem Objekt existieren, um es zu verstecken.',
	'mimeType' : 'Dateityp',
	'preview' : 'Vorschau',
	'Copy' : 'Kopieren',
	'Cut' : 'Ausschneiden',
	'Completely transparent objects are not allowed.':'Komplett transparente Objekte sind nicht erlaubt.',
	'onMobile' : 'Zugriff Smartphone',
	'select properties' : 'Eigenschaften auswählen',
	'undirected' : 'ungerichtet',
	'object as target' : 'Objekt als Ziel',
	'object as source' : 'Objekt als Quelle',
	'bidirectional' : 'bidirektional',
	'change properties' : 'Eigenschaften ändern',
	'direction' : 'Richtung',
    'destination' : 'Ziel',
	'stroke' : 'Linie',
	'dotted' : 'gepunktet',
	'dashed' : 'gestrichelt',
	'style' : 'Stil',
	'save' : 'speichern',
	'distance between object and link' : 'Abstand zwischen Objekt und Link',
    'Create new Subroom' : 'Neuen Unterraum erstellen',
    'Cancel' : 'Abbrechen',
    'Okay' : 'Auswählen',
	'open destination on double-click' : 'Ziel mit Doppelklick öffnen',
	'open in' : 'Ziel öffnen in',
	'Open destination' : 'Ziel öffnen',
	'Target Selection' : 'Zielauswahl',
	'Show objects' : 'Objekte anzeigen',
	'Copy selected format attributes' : 'Übertrage selektierte Eigenschaften',
	'Copy format attributes' : 'Übertragung der Eigenschaften eines Objektes',
	'copy format' : 'Übertrage Formatierung',
	'Please select a destination or enter a URL' : 'Bitte wählen Sie ein Ziel oder geben Sie eine URL ein',
	'Please enter a valid URL' : 'Bitte geben Sie eine gültige URL ein',
	'Internal' : 'Intern',
	'External' : 'Extern'
	}
);

GeneralObject.setTranslations('en',{
        'External' : 'External',
        'object.show.roles.permissions': "Show roles and permissions"
    }
);