GeneralObject.setTranslations('de',{
	'GraphicalObject':'Grafisches Objekt',
	'name':'Name',
	'type':'Typ',
	'layer':'Ebene',
	'width':'Breite',
	'height':'Höhe',
	'fillcolor':'Füllfarbe',
	'linecolor':'Linienfarbe',
	'linesize':'Linienstärke',
	'font-family':'Schriftart',
	'font-size':'Schriftgröße',
	'font-color':'Schriftfarbe',
	'Delete':'Löschen',
	'Duplicate':'Duplizieren',
	'Follow':'Folgen',
	'Edit':'Bearbeiten',
	'Link':'Verknüpfen',
	'to front':'Nach vorne',
	'to back':'Nach hinten',
	'locked':'Angeheftet',
	'visible':'Sichtbar',
	'group':'Gruppe',
	'Group':'Gruppieren',
	'Ungroup':'Gruppierung aufheben',
	'shadow':'Schatten',
	'hidden':'Versteckt',
	'id':'ID',
	'x':'X Pos.',
	'y':'Y Pos.',
	'link':'Verknüpfung',
	'no object slected':'Kein Objekt ausgewählt',
	'you need at least one link from or to this object to hide it':'Es muss mindestens eine Verknüpfung von oder zu diesem Objekt existieren, um es zu verstecken.',
	'mimeType' : 'Dateityp',
	'preview' : 'Vorschau',
	'Copy' : 'Kopieren',
	'Cut' : 'Ausschneiden',
	'Completely transparent objects are not allowed.':'Komplett transparente Objekte sind nicht erlaubt.',
	'select properties' : 'Eigenschaften auswählen',
	'undirected' : 'ungerichtet',
	'object as target' : 'Objekt als Ziel',
	'object as source' : 'Objekt als Quelle',
	'bidirectional' : 'bidirektional',
	'change properties' : 'Eigenschaften ändern',
	'direction' : 'Richtung',
	'stroke' : 'Linie',
	'dotted' : 'gepunktet',
	'dashed' : 'gestrichelt',
	'style' : 'Stil',
	'save' : 'speichern'
}
);